name: Execute Drupal's run-tests.sh for this branch

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: 'Execute run-tests.sh'
    runs-on: ubuntu-latest

    steps:
      - name: setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Clone drupal-container
        uses: actions/checkout@v2
        with:
          repository: localgovdrupal/drupal-container
          ref: master

      - name: Create LocalGov Drupal project
        run: composer create-project --stability dev localgovdrupal/localgov-project html

      - name: Save git branch and git repo names to env if not a pull request
        if: github.event_name != 'pull_request'
        run: |
          echo "GIT_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "GIT_REPO=${GITHUB_REPOSITORY}" >> $GITHUB_ENV
      - name: Save git branch and git repo names to env if is a pull request
        if: github.event_name == 'pull_request'
        run: |
          echo "GIT_BRANCH=${GITHUB_HEAD_REF}" >> $GITHUB_ENV
          echo "GIT_REPO=${{ github.event.pull_request.head.repo.full_name }}" >> $GITHUB_ENV
      - name: Setup package source and authentication for the test target
        run: |
          composer --working-dir=html config repositories.1 vcs git@github.com:${GIT_REPO}.git
          composer global config github-oauth.github.com ${{ github.token }}
      - name: Grab test target from this repo
        run: composer --working-dir=html require localgovdrupal/${{ github.event.repository.name }}:"dev-${GIT_BRANCH} as 1.0.x-dev"

      - name: Start Docker environment
        run: docker-compose up -d

      - name: Run tests
        run: ./run-tests.sh
        shell: bash
