name: Execute Mocha tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  MochaThemeTests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node dependencies
        run: npm install

      - run: npm run health-check
