name: Test LocalGov Drupal

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  DrupalUnitTests:

    runs-on: ubuntu-latest

    steps:
      - name: Clone drupal_container
        uses: actions/checkout@v2
        with:
          repository: localgovdrupal/drupal-container
          ref: master

      - name: Create LocalGov Drupal project
        run: composer create-project --stability dev localgovdrupal/localgov-project html

      - name: Setup package source for the test target
        run: |
          composer --working-dir=html config repositories.1 vcs git@github.com:${{ github.repository }}.git
          composer global config github-oauth.github.com ${{ github.token }}

      - name: Extract Git branch name outside of a pull request
        if: github.event_name != 'pull_request'
        run: echo "::set-env name=GIT_BRANCH::${GITHUB_REF#refs/heads/}"

      - name: Extract Git branch name from a pull request
        if: github.event_name == 'pull_request'
        run: echo "::set-env name=GIT_BRANCH::${GITHUB_HEAD_REF}"

      - name: Grab test target
        run: composer --working-dir=html require ${{ github.repository }}:"dev-${GIT_BRANCH} as 1.0.x-dev"

      - name: Start Docker environment
        run: docker-compose up -d

      - name: Run tests
        run: ./run-tests.sh
        shell: bash

  MochaThemeTests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 10.x, 12.x, 14.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
        shell: bash
        working-directory: client

      - run: npm run health-check
        shell: bash
        working-directory: client
